var deck = [

	{name: 'h2',suit: 'h',rank: '2',value: 2},
	{name: 'h3',suit: 'h',rank: '3',value: 3},
	{name: 'h4',suit: 'h',rank: '4',value: 4},
	{name: 'h5',suit: 'h',rank: '5',value: 5},
	{name: 'h6',suit: 'h',rank: '6',value: 6},
	{name: 'h7',suit: 'h',rank: '7',value: 7},
	{name: 'h8',suit: 'h',rank: '8',value: 8},
	{name: 'h9',suit: 'h',rank: '9',value: 9},
	{name: 'h10',suit: 'h',rank: '10',value: 10},
	{name: 'hJ',suit: 'h',rank: 'J',value: 11},
	{name: 'hQ',suit: 'h',rank: 'Q',value: 12},
	{name: 'hK',suit: 'h',rank: 'K',value: 13},
	{name: 'hA',suit: 'h',rank: 'A',value: 14},
	{name: 'c2',suit: 'c',rank: '2',value: 2},
	{name: 'c3',suit: 'c',rank: '3',value: 3},
	{name: 'c4',suit: 'c',rank: '4',value: 4},
	{name: 'c5',suit: 'c',rank: '5',value: 5},
	{name: 'c6',suit: 'c',rank: '6',value: 6}

]

var fullDeck = [

	{name: 'h2',suit: 'h',rank: '2',value: 2},
	{name: 'h3',suit: 'h',rank: '3',value: 3},
	{name: 'h4',suit: 'h',rank: '4',value: 4},
	{name: 'h5',suit: 'h',rank: '5',value: 5},
	{name: 'h6',suit: 'h',rank: '6',value: 6},
	{name: 'h7',suit: 'h',rank: '7',value: 7},
	{name: 'h8',suit: 'h',rank: '8',value: 8},
	{name: 'h9',suit: 'h',rank: '9',value: 9},
	{name: 'h10',suit: 'h',rank: '10',value: 10},
	{name: 'hJ',suit: 'h',rank: 'J',value: 11},
	{name: 'hQ',suit: 'h',rank: 'Q',value: 12},
	{name: 'hK',suit: 'h',rank: 'K',value: 13},
	{name: 'hA',suit: 'h',rank: 'A',value: 14},
	{name: 'c2',suit: 'c',rank: '2',value: 2},
	{name: 'c3',suit: 'c',rank: '3',value: 3},
	{name: 'c4',suit: 'c',rank: '4',value: 4},
	{name: 'c5',suit: 'c',rank: '5',value: 5},
	{name: 'c6',suit: 'c',rank: '6',value: 6},
	{name: 'c7',suit: 'c',rank: '7',value: 7},
	{name: 'c8',suit: 'c',rank: '8',value: 8},
	{name: 'c9',suit: 'c',rank: '9',value: 9},
	{name: 'c10',suit: 'c',rank: '10',value: 10},
	{name: 'cJ',suit: 'c',rank: 'J',value: 11},
	{name: 'cQ',suit: 'c',rank: 'Q',value: 12},
	{name: 'cK',suit: 'c',rank: 'K',value: 13},
	{name: 'cA',suit: 'c',rank: 'A',value: 14},
	{name: 's2',suit: 's',rank: '2',value: 2},
	{name: 's3',suit: 's',rank: '3',value: 3},
	{name: 's4',suit: 's',rank: '4',value: 4},
	{name: 's5',suit: 's',rank: '5',value: 5},
	{name: 's6',suit: 's',rank: '6',value: 6},
	{name: 's7',suit: 's',rank: '7',value: 7},
	{name: 's8',suit: 's',rank: '8',value: 8},
	{name: 's9',suit: 's',rank: '9',value: 9},
	{name: 's10',suit: 's',rank: '10',value: 10},
	{name: 'sJ',suit: 's',rank: 'J',value: 11},
	{name: 'sQ',suit: 's',rank: 'Q',value: 12},
	{name: 'sK',suit: 's',rank: 'K',value: 13},
	{name: 'sA',suit: 's',rank: 'A',value: 14},
	{name: 'd2',suit: 'd',rank: '2',value: 2},
	{name: 'd3',suit: 'd',rank: '3',value: 3},
	{name: 'd4',suit: 'd',rank: '4',value: 4},
	{name: 'd5',suit: 'd',rank: '5',value: 5},
	{name: 'd6',suit: 'd',rank: '6',value: 6},
	{name: 'd7',suit: 'd',rank: '7',value: 7},
	{name: 'd8',suit: 'd',rank: '8',value: 8},
	{name: 'd9',suit: 'd',rank: '9',value: 9},
	{name: 'd10',suit: 'd',rank: '10',value: 10},
	{name: 'dJ',suit: 'd',rank: 'J',value: 11},
	{name: 'dQ',suit: 'd',rank: 'Q',value: 12},
	{name: 'dK',suit: 'd',rank: 'K',value: 13},
	{name: 'dA',suit: 'd',rank: 'A',value: 14}

]